sap:
  system: P25

data:
  fbl3n_layout: TEXT_UPDATER
  fbl5n_layout: TEXT_UPDATER
  report_name: report.xlsx
  sheet_name: Data

messages:
  requests:
    account: # name of the account
    mailbox: # name of the mailbox
    server:  # name of the host server
  notifications:
    send: True
    sender:   # mail address of the sender
    subject:  # notification subject
    host:     # host server of the sender account
    port:     # port nmber of the sender account
